
import React from 'react';
import {
  ClipboardList,
  Wrench,
  CheckCircle2,
  Truck,
  Clock,
  LayoutDashboard,
  LayoutGrid,
  Users,
  Car,
  Bell,
  Package,
  StickyNote,
  FileCode
} from 'lucide-react';
import { ServiceStatus } from '../types';

export const STATUS_COLORS = {
  [ServiceStatus.PENDENTE]: 'bg-slate-100 text-slate-600 border-slate-200',
  [ServiceStatus.EM_ANDAMENTO]: 'bg-purple-100 text-purple-700 border-purple-200',
  [ServiceStatus.LEMBRETE]: 'bg-amber-100 text-amber-700 border-amber-200',
  [ServiceStatus.PRONTO]: 'bg-green-100 text-green-700 border-green-200',
  [ServiceStatus.ENTREGUE]: 'bg-blue-100 text-blue-700 border-blue-200',
};

export const STATUS_ICONS = {
  [ServiceStatus.PENDENTE]: <Clock className="w-3.5 h-3.5" />,
  [ServiceStatus.EM_ANDAMENTO]: <Wrench className="w-3.5 h-3.5" />,
  [ServiceStatus.LEMBRETE]: <StickyNote className="w-3.5 h-3.5" />,
  [ServiceStatus.PRONTO]: <CheckCircle2 className="w-3.5 h-3.5" />,
  [ServiceStatus.ENTREGUE]: <Truck className="w-3.5 h-3.5" />,
};

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Painel', icon: <LayoutGrid size={20} /> },
  { id: 'vehicles', label: 'Veículos', icon: <Car size={20} /> },
  { id: 'templates', label: 'Fichas', icon: <FileCode size={20} /> },
  { id: 'clients', label: 'Clientes', icon: <Users size={20} /> },
  { id: 'settings', label: 'Ajustes', icon: <Bell size={20} /> },
];

export const VEHICLE_CATALOG_INITIAL = [
  { brand: 'Abarth', model: 'Pulse' },
  { brand: 'Audi', model: 'A3' },
  { brand: 'Audi', model: 'Q3' },
  { brand: 'BMW', model: 'Série 3' },
  { brand: 'BYD', model: 'Dolphin' },
  { brand: 'Chevrolet', model: 'Onix' },
  { brand: 'Chevrolet', model: 'Tracker' },
  { brand: 'Fiat', model: 'Strada' },
  { brand: 'Fiat', model: 'Toro' },
  { brand: 'Fiat', model: 'Argo' },
  { brand: 'Ford', model: 'Ranger' },
  { brand: 'Honda', model: 'Civic' },
  { brand: 'Honda', model: 'HR-V' },
  { brand: 'Hyundai', model: 'HB20' },
  { brand: 'Hyundai', model: 'Creta' },
  { brand: 'Jeep', model: 'Renegade' },
  { brand: 'Jeep', model: 'Compass' },
  { brand: 'Nissan', model: 'Kicks' },
  { brand: 'Peugeot', model: '208' },
  { brand: 'Renault', model: 'Kwid' },
  { brand: 'Toyota', model: 'Corolla' },
  { brand: 'Toyota', model: 'Hilux' },
  { brand: 'Volkswagen', model: 'Gol' },
  { brand: 'Volkswagen', model: 'Polo' },
  { brand: 'Volkswagen', model: 'T-Cross' },
];

export const INITIAL_COLORS = [
  { name: 'Branco Puro', hex: '#FFFFFF', finish: 'gloss' },
  { name: 'Branco Gelo', hex: '#F8FBFF', finish: 'perolizado suave' },
  { name: 'Branco Pérola', hex: '#FFFDF8', finish: 'perolizado' },
  { name: 'Branco Off-White', hex: '#F2F0E6', finish: 'creme claro' },
  { name: 'Marfim', hex: '#F7EEDD', finish: 'tom quente' },
  { name: 'Bege Claro', hex: '#E9D7B9', finish: 'sólido' },
  { name: 'Prata Metálico', hex: '#C0C0C0', finish: 'metálico' },
  { name: 'Prata Escovado', hex: '#B9BFC3', finish: 'metálico' },
  { name: 'Alumínio', hex: '#A9AEB0', finish: 'metálico' },
  { name: 'Cinza Claro', hex: '#D3D3D3', finish: 'sólido' },
  { name: 'Cinza Prata', hex: '#BFC1C2', finish: 'sólido' },
  { name: 'Cinza Médio', hex: '#9EA3A6', finish: 'sólido' },
  { name: 'Cinza Chumbo', hex: '#6E7376', finish: 'sólido' },
  { name: 'Grafite', hex: '#4A4F52', finish: 'metálico' },
  { name: 'Antracite', hex: '#2F3234', finish: 'metálico' },
  { name: 'Preto Puro', hex: '#000000', finish: 'sólido' },
  { name: 'Preto Onyx', hex: '#0B0B0B', finish: 'sólido' },
  { name: 'Preto Perolizado', hex: '#0D0D10', finish: 'perolizado' },
  { name: 'Carvão', hex: '#1C1F22', finish: 'sólido' },
  { name: 'Cinza Concreto', hex: '#7F8487', finish: 'sólido' },
  { name: 'Vermelho Puro', hex: '#C21807', finish: 'sólido' },
  { name: 'Vermelho Ferrari', hex: '#FF2800', finish: 'vivo' },
  { name: 'Vermelho Borgonha', hex: '#800020', finish: 'vinho' },
  { name: 'Bordô', hex: '#5B0E0E', finish: 'sólido' },
  { name: 'Vinho Metálico', hex: '#4A0A0A', finish: 'metálico' },
  { name: 'Vinho Perolizado', hex: '#3D0B0B', finish: 'perolizado' },
  { name: 'Vermelho Candy', hex: '#B80F0A', finish: 'candy paint' },
  { name: 'Vermelho Cereja', hex: '#9B111E', finish: 'sólido' },
  { name: 'Vermelho Rubi', hex: '#8B0000', finish: 'sólido' },
  { name: 'Vermelho Coral', hex: '#FF4040', finish: 'sólido' },
  { name: 'Laranja Puro', hex: '#FF6F00', finish: 'sólido' },
  { name: 'Laranja Metálico', hex: '#D45D12', finish: 'metálico' },
  { name: 'Âmbar', hex: '#D4AF37', finish: 'dourado claro' },
  { name: 'Ouro Metálico', hex: '#B8860B', finish: 'metálico' },
  { name: 'Amarelo Sol', hex: '#FFD700', finish: 'sólido' },
  { name: 'Amarelo Canário', hex: '#FFEF00', finish: 'sólido' },
  { name: 'Amarelo Mostarda', hex: '#C59D00', finish: 'sólido' },
  { name: 'Azul Puro', hex: '#0D47A1', finish: 'sólido' },
  { name: 'Azul Royal', hex: '#4169E1', finish: 'sólido' },
  { name: 'Azul Marinho', hex: '#001F3F', finish: 'sólido' },
  { name: 'Azul Petróleo', hex: '#013040', finish: 'sólido' },
  { name: 'Azul Celeste', hex: '#87CEEB', finish: 'sólido' },
  { name: 'Azul Metálico', hex: '#3B73C6', finish: 'metálico' },
  { name: 'Azul Elétrico', hex: '#0074FF', finish: 'vivo' },
  { name: 'Verde Floresta', hex: '#0B6623', finish: 'sólido' },
  { name: 'Verde Esmeralda', hex: '#009874', finish: 'sólido' },
  { name: 'Verde Militar', hex: '#6B8E23', finish: 'fosco' },
  { name: 'Marbom Café', hex: '#4B2E2E', finish: 'sólido' },
  { name: 'Cobre Metálico', hex: '#B87333', finish: 'metálico' },
  { name: 'Roxo Metálico', hex: '#6F2DA8', finish: 'metálico' },
  { name: 'Preto Matte', hex: '#0E0E0E', finish: 'fosco' },
  { name: 'Champagne', hex: '#F7E7CE', finish: 'perolizado' },
];
